[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/login.html"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard.html"
  status = 200

[functions]
  node_bundler = "esbuild"
